name: Update `posted_at`
on:
  push:
    paths:
      - "**/*.md"

jobs:
  update:
    name: sed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: extract diffs
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: "*.md"
      - name: Run sed
        run: |
          echo ${{ env.GIT_DIFF }}
          cat <<EOF | bash -
          for file in ${{ env.GIT_DIFF }}; do
            sed -i '0,/^posted_at:\ .*\$/ s/^posted_at:\ .*\$/posted_at:\ $(TZ=asia/tokyo date '+%Y-%m-%d')/' 
          done
          EOF
      - name: commit formatted file
        run: |
          git config user.name = "github-actions"
          git config user.email = "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "auto format by github actions" --allow-empty
          git push origin ${{ steps.extract_branch.outputs.BRANCH_NAME  }}
