name: Update `posted_at` automatically
on:
  push:
    paths:
      - "**/*.md"

jobs:
  update:
    name: run sed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setting for multi-byte
        run: |
          git config --global core.quotepath false
      - name: extract diffs
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: "**/*.md"
      - name: Run sed
        run: |
          files=(${{ env.GIT_DIFF }})
          for file in "${files[@]}"; do
            cmd="sed -i '0,/^posted_at:\ .*\$/ s/^posted_at:\ .*\$/posted_at:\ $(TZ=asia/tokyo date "+%Y-%m-%d")/' ${file}"
            eval ${cmd}
          done
      - name: Auto commit
        run: |
            git config user.name = "github-actions"
            git config user.email = "github-actions[bot]@users.noreply.github.com"
            git add -u
            git commit -m ":robot: Update the date automatically."
            git push origin
